# Generated by Django 3.0.9 on 2020-08-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hq_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
