# Generated by Django 3.0.9 on 2020-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('target', models.IntegerField()),
                ('raised', models.IntegerField()),
            ],
        ),
    ]
