# Generated by Django 3.0.9 on 2020-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('iframe', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
