# Generated by Django 3.0.9 on 2020-08-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_name',
            field=models.CharField(blank=True, default='Unkown Author', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_remarks',
            field=models.TextField(blank=True, default='No remarks', null=True),
        ),
    ]
