# Generated by Django 3.0.9 on 2020-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200808_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extract',
            field=models.TextField(blank=True, default='No quote', null=True),
        ),
    ]
